In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sample_500.csv to sample_500.csv

In [ ]:
import pandas as pd
import io

# Get the uploaded file name
file_name = list(uploaded.keys())[0]

# Read pipe-delimited file into pandas DataFrame
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

In [ ]:
df.columns

Index(['id', 'tid', 'bates', 'type', 'description', 'title', 'author',
       'mentioned', 'attending', 'copied', 'recipient', 'redacted',
       'collection_name', 'pages', 'exhibit_number', 'document_date',
       'date_added_ucsf', 'date_modified_ucsf', 'date_added_industry',
       'date_modified_industry', 'date_produced', 'date_shipped',
       'deposition_date', 'date_privilege_logged', 'case', 'industry', 'drug',
       'adverse_ruling', 'area', 'bates_alternate', 'box', 'brand', 'country',
       'language', 'court', 'format', 'express_waiver', 'file', 'genre',
       'keywords', 'bates_master', 'other_number', 'request_number',
       'minnesota_request_number', 'privilege_code', 'topic', 'witness',
       'cited', 'availability', 'grant_number', 'source', 'folder', 'series',
       'chemical', 'food', 'rights', 'ocr_text'],
      dtype='object')

In [ ]:
# Display first few rows
df

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,cited,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text
0,kqjj0045,vxr76b00,107318467Exhibit1114,,,CAC VIII Smoking Issues,,British American Tobacco Industry (BAT),,,...,,"public, no restrictions",,,,,,,,3^V7 CAC VIII SMOKING ISSUES The key...
1,ksmj0045,pct76b00,2047562142-2047562143,,,Subject: Sales Force Support for Ask First/It'...,"Merlo, Ellen","Philip Morris Cos., Inc.",,"Johnson, C, Szymanczyk, M",...,,"public, no restrictions",,,,,,,,PHILIP MORRIS USA INTER-OFFICE CORRESPONDEN...
2,ksjj0045,bzr76b00,2047120443-5047120501Exhibit1,,,"Philip Morris Companies, Inc. 1984 Annual Report",,"Philip Morris Cos., Inc.",,,...,,"public, no restrictions",,,,,,,,"b^?3 /�K TRIAL EXHIBIT 17,624 pgNbr=1..."
3,zqpj0045,hfu76b00,TIMN200696-TIMN200704,,,A Review of Helping Youth Decide State Boards ...,"Gilbert, Narma S PhD",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,TOB08615.46 Pagel of 10 A TIE VIEW OF H...
4,gqlx0045,lpm76b00,666052815,,,Subject: Future Kool Creative Presentations - ...,"Reid, F T",Brown and Williamson Tobacco Corp.,,,...,,"public, no restrictions",,,,,,,,<ocr>Subject: Future KCOL Creative Preeentetlo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,znhj0045,ocr76b00,552378711-502378733,,,CBS Reports: The Golden Leaf,"Radio, TV Reports Inc",Tobacco Institute,,,...,,"public, no restrictions",,,,,,,,"RADIO IV REPORTS, ,nc. 4701 WILLARD AVENUE,..."
495,jslj0045,sss76b00,C1-94-8565,,,"Minnesota vs. Tobacco April 8, 1998","Blue, Cross and Blue Shield of Minnesota, Stat...",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,The Putnam Pit: Minnesota tobacco trial; April...
496,rflj0045,als76b00,Exhibit18799,,,Scientists Funded By Tobacco Say Smoking Is Ha...,"Associated, Press, Star, Tribune",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,V ) Wednesday/June iib/tyyi/bttr I noun* ...
497,syyj0045,dut76b00,YoAsNON19990205.Ar,,,Anti-Smoking Campaign Unsuccessful Among Schoo...,,Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,"529-y Michael Ctimmings Ph, 01:26 ..."
498,xjpx0045,qyn76b00,82786447-82786456,,,Screening Questionnaire,"FRC, Research Corporation",Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,<ocr>FRC RESEARCH CORPORATION NEWPORT PAIRED C...

In [ ]:
df.iloc[0]['ocr_text']

'3^V7    CAC VIII    SMOKING  ISSUES    The key issues we would like to discuss are  -    CD            Does the  recent epidemiological evidence offer anv    comfort to the Tobacco Industry?    (Dr* *h2�!L    y will introduce this subject}?^      (     \'  Thornton    �    �:iH* 41"- sa-sts-r    surink both the size and the profitability of the business through  fiscal measures.     If the  former    �Z *% f "e **�* what aevice ia being given ^r should be given,  to Governments by the Tobacco Industry and/or BAT on the subject of enhancing revenue without damaging the tobacco burets  *    TRIAL EXHIBIT    11,143    Osl    ^ATP.t _     A/i.....___^____T                          ^ pgNbr=1 '

In [ ]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.47)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=26a2319f85460749c6fcbec737cec9971df526e57b8c98fa2a217d3200d9a699
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
from pandasql import sqldf

# Global query function
pysqldf = lambda q: sqldf(q, globals())

In [ ]:
sql = """
SELECT *
FROM (
    SELECT *
    FROM df
    WHERE mentioned = 'Non-Tobacco Company'
    LIMIT 50
)

UNION ALL

SELECT *
FROM (
    SELECT *
    FROM df
    WHERE mentioned != 'Non-Tobacco Company'
       OR mentioned IS NULL
    LIMIT 50
)
"""

In [ ]:
df_mentioned = pysqldf(sql)

In [ ]:
df_mentioned

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,cited,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text
0,zqpj0045,hfu76b00,TIMN200696-TIMN200704,,,A Review of Helping Youth Decide State Boards ...,"Gilbert, Narma S PhD",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,TOB08615.46 Pagel of 10 A TIE VIEW OF H...
1,pnpx0045,kbo76b00,500201480,,,Re: Recent Stopage of Advertising by Means of ...,"Wilson, Dwight",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,"<ocr>, llwi bht 1>> I son 1801 Hampshire Grand..."
2,htpj0045,qgu76b00,03614223,,,Gallup Youth Survey,"Gallup, George",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,/?/� 03614223 j4 i- Mi _ i;- ...
3,tnyj0045,ott76b00,03025116-03025123,,,"TMA Issues Monitor Update Issue Vol. 3, No. 5","Tobacco, Merchants Associationof the US",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,"<ocr>Vol. 3, No. 5 1Q 1982 STATE HIGHLIGHTS,;:..."
4,yzcj0045,kjp76b00,03586171-03586174,,,Re: Subcommittee on Oversight and Investigatio...,"Moss, John E",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,"<ocr>C May 1, 19'78 Mr. Chester L. Posey, Pres..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,rmfj0045,diq76b00,670585237-670585256,,,Market Dynamics,,Brown and Williamson Tobacco Corp.,,,...,,"public, no restrictions",,,,,,,,"MARKET DYNAMICS $ A-GKCfROU ND, DAN VISANESC..."
96,yrkj0045,lis76b00,1003717691-1003717694,,,"Hamburg Meeting June 5, 1979",,R.J. Reynolds Tobacco Co.,,,...,,"public, no restrictions",,,,,,,,"<ocr>-2- HAMBURG MEETING June 5, 1979 Tom 0sde..."
97,hljj0045,qur76b00,660913609-660913633Exhibit13,,,[Re:] Smoker Compensation Study: Paper 16-Huma...,"Brooks, G O",British American Tobacco Industry (BAT),,,...,,"public, no restrictions",,,,,,,,(B&VV) PROTECTED BY MINNESOTA TOBACCO LITIGATI...
98,pxyj0045,iqt76b00,2047035909,,,Philip Morris Announces Initiatives to Prevent...,,"Philip Morris Cos., Inc.",,,...,,"public, no restrictions",,,,,,,,"<ocr>For Immediate Release Contact: June -, 19..."
99,ltcj0045,rip76b00,2041817752-2041817759,,,Secret U.S. Hispanic Case Study,,"Philip Morris Cos., Inc.",,,...,,"public, no restrictions",,,,,,,,<ocr>SECRET U.S. HISPANIC CASE STUDY pgNbr=1 I...

In [ ]:
# does the sentiment differ for non-tobacco produced or tobacco-produced?
# do they differ substantially in subject matter (health, entertainment, outdoors)?

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.1.4)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 6.3 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [ ]:
def vader_first_500(text):
    if not isinstance(text, str) or not text.strip():
        return None
    short_text = text[:500]
    return analyzer.polarity_scores(short_text)['compound']

df['vader_compound_500'] = df['ocr_text'].apply(vader_first_500)

In [ ]:
df

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text,vader_compound_500
0,kqjj0045,vxr76b00,107318467Exhibit1114,,,CAC VIII Smoking Issues,,British American Tobacco Industry (BAT),,,...,"public, no restrictions",,,,,,,,3^V7 CAC VIII SMOKING ISSUES The key...,0.7752
1,ksmj0045,pct76b00,2047562142-2047562143,,,Subject: Sales Force Support for Ask First/It'...,"Merlo, Ellen","Philip Morris Cos., Inc.",,"Johnson, C, Szymanczyk, M",...,"public, no restrictions",,,,,,,,PHILIP MORRIS USA INTER-OFFICE CORRESPONDEN...,0.8988
2,ksjj0045,bzr76b00,2047120443-5047120501Exhibit1,,,"Philip Morris Companies, Inc. 1984 Annual Report",,"Philip Morris Cos., Inc.",,,...,"public, no restrictions",,,,,,,,"b^?3 /�K TRIAL EXHIBIT 17,624 pgNbr=1...",0.9442
3,zqpj0045,hfu76b00,TIMN200696-TIMN200704,,,A Review of Helping Youth Decide State Boards ...,"Gilbert, Narma S PhD",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,TOB08615.46 Pagel of 10 A TIE VIEW OF H...,0.6046
4,gqlx0045,lpm76b00,666052815,,,Subject: Future Kool Creative Presentations - ...,"Reid, F T",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,<ocr>Subject: Future KCOL Creative Preeentetlo...,0.9151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,znhj0045,ocr76b00,552378711-502378733,,,CBS Reports: The Golden Leaf,"Radio, TV Reports Inc",Tobacco Institute,,,...,"public, no restrictions",,,,,,,,"RADIO IV REPORTS, ,nc. 4701 WILLARD AVENUE,...",0.8834
495,jslj0045,sss76b00,C1-94-8565,,,"Minnesota vs. Tobacco April 8, 1998","Blue, Cross and Blue Shield of Minnesota, Stat...",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,The Putnam Pit: Minnesota tobacco trial; April...,0.0000
496,rflj0045,als76b00,Exhibit18799,,,Scientists Funded By Tobacco Say Smoking Is Ha...,"Associated, Press, Star, Tribune",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,V ) Wednesday/June iib/tyyi/bttr I noun* ...,-0.1531
497,syyj0045,dut76b00,YoAsNON19990205.Ar,,,Anti-Smoking Campaign Unsuccessful Among Schoo...,,Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"529-y Michael Ctimmings Ph, 01:26 ...",0.1531
498,xjpx0045,qyn76b00,82786447-82786456,,,Screening Questionnaire,"FRC, Research Corporation",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,<ocr>FRC RESEARCH CORPORATION NEWPORT PAIRED C...,0.6289

In [ ]:
sql_sentiment = """
SELECT
  CASE
    WHEN mentioned = 'Non-Tobacco Company' THEN 'Non-Tobacco Company'
    ELSE 'Other'
  END AS mentioned_group,
  AVG(vader_compound_500)                    AS avg_sentiment,
  SUM(CASE WHEN vader_compound_500 IS NOT NULL THEN 1 ELSE 0 END) AS n_non_null,
  COUNT(*)                                   AS total_rows
FROM df
GROUP BY mentioned_group;
"""

In [ ]:
pysqldf(sql_sentiment)

       mentioned_group  avg_sentiment  n_non_null  total_rows
0  Non-Tobacco Company       0.189271          56          56
1                Other       0.354463         442         443